version: "3.3"

services:
  ################### Backend #########################
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 1234:1234
    restart: always
    depends_on:
      - db
  ################### Base de Datos #########################
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    container_name: database
    ports:
      - 2345:5432
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      POSTGRES_PASSWORD: my-secret-pw    
      POSTGRES_USER: docker