CREATE DATABASE cobrando_bpo
    WITH
    OWNER = docker
    CONNECTION LIMIT = -1;

\c cobrando_bpo;

CREATE TABLE DEPARTAMENTOS(
	codigo SERIAL NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	presupuesto DOUBLE PRECISION NOT NULL,
	PRIMARY KEY(codigo)
);

CREATE TABLE EMPLEADOS(
	codigo SERIAL NOT NULL,
	nit VARCHAR(9) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	apellido1 VARCHAR(100) NOT NULL,
	apellido2 VARCHAR (100),
	codigo_departamento INT NOT NULL,
	PRIMARY KEY(codigo)
);

ALTER TABLE EMPLEADOS 
ADD CONSTRAINT dep_emp 
FOREIGN KEY (codigo_departamento) 
REFERENCES DEPARTAMENTOS(codigo);

INSERT INTO DEPARTAMENTOS (NOMBRE, PRESUPUESTO) VALUES ('DESARROLLO BACKEND', 100000);
INSERT INTO DEPARTAMENTOS (NOMBRE, PRESUPUESTO) VALUES ('DESARROLLO FRONTEND', 100000);
INSERT INTO DEPARTAMENTOS (NOMBRE, PRESUPUESTO) VALUES ('DESARROLLO FULLSTACK', 100000);
INSERT INTO DEPARTAMENTOS (NOMBRE, PRESUPUESTO) VALUES ('DESARROLLO ANDROID', 100000);
INSERT INTO DEPARTAMENTOS (NOMBRE, PRESUPUESTO) VALUES ('DESARROLLO IOS', 100000);